### ISSUE TITLE
Changes to the tutorial code

### ISSUE THREAD

**Issue by gtatsios** [eigemx/unvpp#1]
In the tutorial code the following changes should be made so that it works with the current version of unvpp.

Line 20: 
From: `<< mesh.unitsSystem.value_or(unvpp::UnitsSystem()).repr`
To: `<< mesh.units_system.value_or(unvpp::UnitsSystem()).repr`

Line 36:
From: `<< group.name `
To: `<< group.name() `

Line 38:
From: `<< group.eIndices.size()`
To: `<< group.elements_ids().size()`

**Comment by eigemx** [comment]
Thanks @gtatsios !
Tutorial is now updated as per the latest API version.

**Comment by eigemx** [comment]
Thanks @gtatsios !
Tutorial is now updated as per the latest API version.
